### ISSUE TITLE
Is there any open source plan or scheduling of XQUIC?

### ISSUE THREAD

**Issue by ArthurCChen** [alibaba/xquic#1]
Many developer friends are looking forward to XQUIC codes since it will contain the first opensource QUIC client implementation on mobile phones.

**Comment by Kulsk** [comment]
sorry that we delayed so long, we will open the code recently

**Comment by ArthurCChen** [comment]
Thanks for the response! And still sorry for another disturbing. 
Do you think the codes would be opened before Christmas of 2021? I might need to schedule my work plan according to your plan. Thanks!
