### ISSUE TITLE
[Feature]: when will xquic support windows? 

### ISSUE THREAD

**Issue by baluoteliz** [alibaba/xquic#105]
### Before request a new feature

- [X] I have searched the [issues](https://github.com/alibaba/xquic/issues) of this repository and believe that this is not a duplicate.

### Describe the feature you'd like supported

I need xquic support windows platform.

**Comment by RuiqiZhou** [comment]
A contributor is working on this feature and it is not certain when it will be completed. Progress will be synchronised here.

**Comment by yuanbo-zhang** [comment]
Dear      您好，邮件我已收到 ！BestwishThink's张渊博
