### ISSUE TITLE
[Bug]: build error

### ISSUE THREAD

**Issue by trip-ibu** [alibaba/xquic#12]
### What happened?

Build error happens when I run "make -j"

### Steps To Reproduce

Follow the README

### Relevant log output

```shell
ld: unknown option: --whole-archive
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libxquic.dylib] Error 1
make[1]: *** [CMakeFiles/xquic.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 90%] Built target xquic-static
make: *** [all] Error 2
```

**Comment by Kulsk** [comment]
what version of gcc you are using? it seems that gcc with higher version is required, we use 4.8.5 for building xquic, but latest boringssl might require higher

**Comment by trip-ibu** [comment]
GCC 4.2.1. I will upadte gcc  and try again, Thanks for your response

**Comment by trip-ibu** [comment]
Upgrade GCC to lates version and still not work:
gcc --version 
gcc (Homebrew GCC 11.2.0_3) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Kulsk** [comment]
> Upgrade GCC to lates version and still not work:
> gcc --version 
> gcc (Homebrew GCC 11.2.0_3) 11.2.0
> Copyright (C) 2021 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

check if the gcc used is the one you installed, try to print the CC variable

**Comment by RuiqiZhou** [comment]
Is the problem solved after upgrade gcc? It seems that #16 is having a problem similar to yours, you can discuss it with people in the discussion forum.

**Comment by bolshoytoster** [comment]
The issue is because of ld, not gcc. If you remove `--whole-archive -Wl,` from line 245 in `CMakeLists.txt` it should work.
```sh
sed -i 's/--whole-archive -Wl,//g' CMakeLists.txt
```

**Comment by waruqi** [comment]
This is because you are compiling xquic on macOS, but `if(PLATFORM MATCHES "mac")` in cmakelists returns false which causes this problem.

A workaround is to additionally define `-DPLATFORM=mac` as cflags and pass it to cmake when compiling. Or patch CMakelists.txt

we can aslo use xmake/xrepo to build and use it, this library has been added xmake-repo repository. https://github.com/xmake-io/xmake-repo/blob/master/packages/x/xquic/xmake.lua

And these patches have been applied to fix it.

Only install library and export it.

```console
$ xrepo install xquic
$ xrepo export -o /xxx/ xquic
``` 

Use [xmake](https://github.com/xmake-io/xmake) to build and use it directly.

```lua
add_requires("xquic")
target("test")
    set_kind("binary")
    add_files("src/*.c")
    add_packages("xquic")
```

**Comment by trip-ibu** [comment]
> This is because you are compiling xquic on macOS, but `if(PLATFORM MATCHES "mac")` in cmakelists returns false which causes this problem.
> 
> A workaround is to additionally define `-DPLATFORM=mac` as cflags and pass it to cmake when compiling. Or patch CMakelists.txt
> 
> we can aslo use xmake/xrepo to build and use it, this library has been added xmake-repo repository. https://github.com/xmake-io/xmake-repo/blob/master/packages/x/xquic/xmake.lua
> 
> And these patches have been applied to fix it.
> 
> Only install library and export all binaries.
> 
> ```
> $ xrepo install xquic
> $ xrepo export -o /xxx/ xquic
> ```
> 
> ```
> $ xrepo install xquic
> note: install or modify (m) these packages (pass -y to skip confirm)?
> in xmake-repo:
>   -> cmake 3.22.1 [from:boringssl,xquic]
>   -> go 1.17.6 [from:boringssl,xquic]
>   -> boringssl 2021.12.29 [from:xquic]
>   -> xquic 2022.01.08 
> please input: y (y/n/m)
> 
>   => install go 1.17.6 .. ok                             
>   => download https://cmake.org/files/v3.22/cmake-3.22.1-macos-universal.tar.gz .. ok
>   => install cmake 3.22.1 .. ok     
>   => install boringssl 2021.12.29 .. ok  
>   => install xquic 2022.01.08 .. ok 
> $ xrepo fetch xquic
> { 
>   { 
>     version = "2022.01.08",
>     static = true,
>     linkdirs = { 
>       "/Users/ruki/.xmake/packages/x/xquic/2022.01.08/6153e85e6d2e4ab9b5c207d956fe8698/lib" 
>     },
>     links = { 
>       "xquic-static" 
>     },
>     license = "Apache-2.0",
>     libfiles = { 
>       "/Users/ruki/.xmake/packages/x/xquic/2022.01.08/6153e85e6d2e4ab9b5c207d956fe8698/lib/libxquic-static.a" 
>     },
>     includedirs = { 
>       "/Users/ruki/.xmake/packages/x/xquic/2022.01.08/6153e85e6d2e4ab9b5c207d956fe8698/include" 
>     } 
>   } 
> }
> ```
> 
> Or use [xmake](https://github.com/xmake-io/xmake) to build and use it directly, do not use xrepo command.
> 
> ```lua
> add_requires("xquic")
> target("test")
>     set_kind("binary")
>     add_files("src/*.c")
>     add_packages("xquic")
> ```
> 
> ```
> $ xmake
> note: install or modify (m) these packages (pass -y to skip confirm)?
> in xmake-repo:
>   -> cmake 3.22.1 [from:boringssl,xquic]
>   -> go 1.17.6 [from:boringssl,xquic]
>   -> boringssl 2021.12.29 [from:xquic]
>   -> xquic 2022.01.08 
> please input: y (y/n/m)
> 
>   => install go 1.17.6 .. ok                             
>   => download https://cmake.org/files/v3.22/cmake-3.22.1-macos-universal.tar.gz .. ok
>   => install cmake 3.22.1 .. ok     
>   => install boringssl 2021.12.29 .. ok  
>   => install xquic 2022.01.08 .. ok 
> [ 25%]: ccache compiling.release src/main.cpp
> /usr/local/bin/ccache /usr/bin/xcrun -sdk macosx clang -c -Qunused-arguments -arch x86_64 -mmacosx-version-min=11.4 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -isystem /Users/ruki/.xmake/packages/x/xquic/2022.01.08/6153e85e6d2e4ab9b5c207d956fe8698/include -isystem /Users/ruki/.xmake/packages/b/boringssl/2021.12.29/6b4d6ed9952d472ba8e7d69e7e216f3f/include -DNDEBUG -o build/.objs/test/macosx/x86_64/release/src/main.cpp.o src/main.cpp
> checking for flags (-MMD -MF) ... ok
> checking for flags (-fdiagnostics-color=always) ... ok
> [ 50%]: linking.release test
> "/usr/bin/xcrun -sdk macosx clang++" -o build/macosx/x86_64/release/test build/.objs/test/macosx/x86_64/release/src/main.cpp.o -arch x86_64 -mmacosx-version-min=11.4 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -stdlib=libc++ -L/Users/ruki/.xmake/packages/x/xquic/2022.01.08/6153e85e6d2e4ab9b5c207d956fe8698/lib -L/Users/ruki/.xmake/packages/b/boringssl/2021.12.29/6b4d6ed9952d472ba8e7d69e7e216f3f/lib -Wl,-x -lxquic-static -lssl -lcrypto -lz
> ```

Problem resolved after add -DPLATFORM=mac flag. Thanks a lot
