### ISSUE TITLE
[Bug]: Division-by-zero exception caused by return value of xqc_pacing_rate_calc()

### ISSUE THREAD

**Issue by Saigut** [alibaba/xquic#127]
### What happened?

Function `xqc_pacing_rate_calc()` can returned 0 in some case (I encountered this problem once, not sure how to reproduce), and causing division-by-zero exception in `xqc_pacing_time_until_send()` at this line:
https://github.com/alibaba/xquic/blob/7f362ee085a4a1eeb48fb7f90a3ae07f24481872/src/transport/xqc_pacing.c#L122

### Steps To Reproduce

I encountered this problem once, not sure how to reproduce.

**Comment by RuiqiZhou** [comment]
Thank you for your feedback, we will fix it as soon as possible.

**Comment by yangfurong** [comment]
> ### What happened?
> Function `xqc_pacing_rate_calc()` can returned 0 in some case (I encountered this problem once, not sure how to reproduce), and causing division-by-zero exception in `xqc_pacing_time_until_send()` at this line:
> 
> https://github.com/alibaba/xquic/blob/7f362ee085a4a1eeb48fb7f90a3ae07f24481872/src/transport/xqc_pacing.c#L122
> 
> ### Steps To Reproduce
> I encountered this problem once, not sure how to reproduce.
> 
> ### Relevant log output
> _No response_

Which congestion control algorithm were you using?

**Comment by Saigut** [comment]
> Which congestion control algorithm were you using?
@yangfurong Maybe cubic, I don't remember that clearly.

**Comment by Saigut** [comment]
@yangfurong
In my view, `xqc_cong_ctl_get_pacing_rate()`, `xqc_cong_ctl_get_cwnd()`, and `srtt` all can cause `pacing_rate` being set to 0. 
It seems the safest way to fix this is to replace all `return pacing_rate;` to `return pacing_rate + 1;`, or check 0 then +1 before `return pacing_rate;`.

**Comment by yangfurong** [comment]
> @yangfurong The safest way to fix this maybe to check return value of `xqc_pacing_rate_calc()` before devide it.

IMO, if the CCA callbacks are properly implemented, checking the return value is redundant. Cuz, every CCA should ensure that its cwnd and pacing_rate never get to zero.

**Comment by Saigut** [comment]
>IMO, if the CCA callbacks are properly implemented, checking the return value is redundant. Cuz, every CCA should ensure that its cwnd and pacing_rate never get to zero.

In addition, is there a risk that `srtt` bigger than `cwnd * 1000000` in` xqc_pacing_rate_calc()`?

**Comment by yangfurong** [comment]
> > IMO, if the CCA callbacks are properly implemented, checking the return value is redundant. Cuz, every CCA should ensure that its cwnd and pacing_rate never get to zero.
> 
> In addition, is there a risk that `srtt` bigger than `cwnd * 1000000` in` xqc_pacing_rate_calc()`?

I don't think so.  The cwnd is at least one MSS, i.e. 1200 bytes in XQUIC.  Therefore, unless srtt is larger than 1200s, which is not possible, the result should be always larger than zero.
