### ISSUE TITLE
[Feature]: FEC/RED functionality in the future?

### ISSUE THREAD

**Issue by adcen0107** [alibaba/xquic#129]
### Before request a new feature

- [X] I have searched the [issues](https://github.com/alibaba/xquic/issues) of this repository and believe that this is not a duplicate.

### Describe the feature you'd like supported

reference to RFC 2198、RFC 2733

**Comment by RuiqiZhou** [comment]
This feature was mentioned previously in #125. It's not in our plans for now, but we'll evaluate it later.

Welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. We appreciate your effort in advance and looking forward to your contribution!

**Comment by adcen0107** [comment]
thanks

**Comment by RuiqiZhou** [comment]
After our discussion and evaluation, this issue may not fit our design or its not common requirement. FEC/RED is not part of the QUIC protocol.
