### ISSUE TITLE
[Bug]: xqc_bbr.c comments or source code error

### ISSUE THREAD

**Issue by adcen0107** [alibaba/xquic#162]
### What happened?

xqc_bbr.c line70~71
/* keep minrtt valid for 10s if it has not been changed */
const uint32_t xqc_bbr2_minrtt_win_size_us = 3000000;

### Steps To Reproduce

just view source code, compare comments or source code

**Comment by lurker-Chen** [comment]
It's a comment error. The value of parameter has been adjusted.
