### ISSUE TITLE
[Bug]:congestion_control cb crash when xqc_connect

### ISSUE THREAD

**Issue by evanyanggithub** [alibaba/xquic#173]
### What happened?

msvc build:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build>vcvars64.bat
mkdir build & cd build
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
nmake

test code:
    xqc_conn_ssl_config_t conn_ssl_config;
    memset(&conn_ssl_config, 0, sizeof(conn_ssl_config));
    conn_ssl_config.session_ticket_data = NULL;
    conn_ssl_config.transport_parameter_data = NULL;

    user_conn->token = NULL;
    user_conn->token_len = 0;

    xqc_conn_settings_t conn_settings = {0};
    conn_settings.pacing_on = 1;
    conn_settings.ping_on = 0;
    conn_settings.cong_ctrl_callback = xqc_bbr_cb;
    conn_settings.cc_params.customize_on = 1;
    conn_settings.cc_params.init_cwnd = 32;
    conn_settings.cc_params.cc_optimization_flags = 0;
    conn_settings.proto_version = XQC_VERSION_V1;
    conn_settings.spurious_loss_detect_on = 0;
    ASP_INFO("Note --> starting xqc_connect !");
    const xqc_cid_t* cid = xqc_connect(user_conn->engine, &conn_settings, user_conn->token, user_conn->token_len,
                                       ASP_CERT_VERIFY_DOMAIN, ASP_XQUIC_ENCRYPT /* No crypt*/, &conn_ssl_config,
                                       user_conn->peer_addr, user_conn->peer_addrlen, XQC_ALPN_TRANSPORT, user_conn);

crash on: src/transport/xqc_send_ctl.c
xqc_send_ctl_create
    if (conn->conn_settings.cong_ctrl_callback.xqc_cong_ctl_init_bbr) {
        send_ctl->ctl_cong_callback = &conn->conn_settings.cong_ctrl_callback;

    } else if (conn->conn_settings.cong_ctrl_callback.xqc_cong_ctl_init) {
        send_ctl->ctl_cong_callback = &conn->conn_settings.cong_ctrl_callback;

    } else {
        send_ctl->ctl_cong_callback = &xqc_cubic_cb;
    }
 
配置的是xqc_bbr_cb ，实际走的是else 
send_ctl->ctl_cong_callback = &xqc_cubic_cb; 
且在这句crash 了：
send_ctl->ctl_cong = xqc_pcalloc(conn->conn_pool, send_ctl->ctl_cong_callback->xqc_cong_ctl_size());
send_ctl->ctl_cong_callback->xqc_cong_ctl_size() 这个调用为空

### Steps To Reproduce

Information and Steps to reproduce the behavior.
the same with what happended

**Comment by RuiqiZhou** [comment]
Hi, as you described in the DingDing group, this bug is occurring because you are using the wrong version, so I will close this issue.

Feel free to open a new issue if you still encounter similar problems with v1.1.0-beta.2.

**Comment by yuanbo-zhang** [comment]
Dear      您好，邮件我已收到 ！BestwishThink's张渊博
