### ISSUE TITLE
[Bug]: xqc_stream.c这里先添加pos到retry链表，紧接着马上删除pos，是否逻辑有问题？

### ISSUE THREAD

**Issue by adcen0107** [alibaba/xquic#174]
### What happened?

      int 
xqc_crypto_stream_send(xqc_stream_t *stream, 
    xqc_list_head_t *crypto_data_list, xqc_pkt_type_t pkt_type)
{
        //process something 

        /* client buffer initial level crypto data */
        if (c->conn_type == XQC_CONN_TYPE_CLIENT
            && stream->stream_encrypt_level == XQC_ENC_LEV_INIT)
        {
            xqc_list_add_tail(pos, &c->retry_crypto_data_buffer);
        }

        xqc_list_del(pos);
        xqc_free(buf);
    }

### Steps To Reproduce

是否是如下逻辑？
        /* client buffer initial level crypto data */
        if (c->conn_type == XQC_CONN_TYPE_CLIENT
            && stream->stream_encrypt_level == XQC_ENC_LEV_INIT)
        {
            xqc_list_add_tail(pos, &c->retry_crypto_data_buffer);
        }
       else
       {
             xqc_list_del(pos);
             xqc_free(buf);
        }

**Comment by RuiqiZhou** [comment]
The new release this month will add support for handling the Retry packet and fix the problem.
