### ISSUE TITLE
[ASOC2022]: XQUIC iOS 集成 demo

### ISSUE THREAD

**Issue by ruiqizhou** [alibaba/xquic#175]
## 背景

- #178 

目前XQUIC开源为纯C代码，提供了C层接口和IOS平台静态库打包脚本，demo方面目前已有C层参考。计划开发IOS平台demo供开发者参考，丰富XQUIC社区跨平台应用生态，帮助IOS开发者更好使用XQUIC库。涉及到的开发内容有：异步事件库、XQUIC接口、网络通信、IOS 应用开发。

## 产出要求
* 学习 XQUIC 并理解接口使用
* 完成 XQUIC iOS 适配开发
* demo支持 QUIC/HTTP3 网络协议收发通信

## ASOC 2022
* 难度：基础
* 导师：@lurker-Chen 
* 联系邮箱：cwt274890@alibaba-inc.com

**Comment by initialj** [comment]
Where‘s the demo？

**Comment by Yanmei-Liu** [comment]
This event is finished, so we closed related issues. Thanks for all the students who participated.
这个活动结束了，因此我们关闭相关的issue，感谢所有的参与同学。

**Comment by ChainHerman** [comment]
demo 在哪？
