### ISSUE TITLE
[ASOC2022]: 多路径QUIC调度算法

### ISSUE THREAD

**Issue by ruiqizhou** [alibaba/xquic#177]
## 背景

- #178 

> https://datatracker.ietf.org/doc/html/draft-lmbdhk-quic-multipath#section-6
> Multipath QUIC implementations also need to include a packet scheduler that decides, among the paths whose congestion window is open, the path over which the next QUIC packet will be sent.  Many factors can influence the definition of these algorithms and their precise definition is outside the scope of this document.  Various packet schedulers have been proposed and implemented, notably for Multipath TCP.  A companion draft [[I-D.bonaventure-iccrg-schedulers](https://datatracker.ietf.org/doc/html/draft-lmbdhk-quic-multipath#ref-I-D.bonaventure-iccrg-schedulers)] provides several general-purpose packet schedulers depending on the application goals.

数据包调度是MPQUIC设计最核心的部分之一，数据包调度器负责确定每个数据包应该由哪个路径（子流）进行发送。本项目要求在XQUIC开源的多路径QUIC实现（XLINK）基础上，实现一套或多套多路径QUIC调度算法（可参考 BLEST、ECF、MuSher、DEMS、STMS、RAVEN 等）。

## 产出要求

* 能够在导师的指导下熟悉并理解相关的代码
* 调研MPQUIC调度算法，理解其原理
* 选择一个MPQUIC调度算法进行实现

## ASOC 2022
* 难度：进阶
* 导师：@RuiqiZhou
* 联系邮箱：dangdang.zrq@alibaba-inc.com

**Comment by Yanmei-Liu** [comment]
This activity is finished. Thank you for all the students who participated.

这个活动结束了，感谢所有参与的同学。
