### ISSUE TITLE
Bug in xqc_write_new_token_to_packet

### ISSUE THREAD

**Issue by Luffbee** [alibaba/xquic#179]
https://github.com/alibaba/xquic/blob/109918f980b3e649f0e7bce4d3bd926a6e44e002/src/transport/xqc_packet_out.c#L672
`xqc_vint_len_by_val` should be used, instead of `xqc_vint_get_2bit`.

**Comment by RuiqiZhou** [comment]
Please follow the templates to write a Bug report.
