### ISSUE TITLE
[Feature]: 使用xquic传输rtmp

### ISSUE THREAD

**Issue by wangpeng1** [alibaba/xquic#190]
### Before request a new feature

- [X] I have searched the [issues](https://github.com/alibaba/xquic/issues) of this repository and believe that this is not a duplicate.

### Describe the feature you'd like supported

目前 是否有单独的接口或者说明 直接使用xquic传输rtmp 包，不使用http 3 等相关接口和验证功能，或者可选在编译的时候去掉多余的spyd部分。

**Comment by RuiqiZhou** [comment]
Is this a question and not a feature request?

If this is a feature request, please describe your requirements in more detail, otherwise please ask a question in the [discussion forum](https://github.com/alibaba/xquic/discussions).

**Comment by hankai17** [comment]
可以试一下我的[quic-fiber](https://github.com/hankai17/quic-fiber)接口试一下 目前传控开发完毕
仍在开发阶段 没有把所有代码上传
