### ISSUE TITLE
[Bug]: memory leak if connection closed during handshake

### ISSUE THREAD

**Issue by Luffbee** [alibaba/xquic#197]
### What happened?

https://github.com/alibaba/xquic/blob/8fab2f91a468dc9f37ba02cca14d032ca8f40353/src/transport/xqc_conn.h#L310-L313

These 3 lists are not cleared when connection destroy, so if the connection is closed during handshake (e.g. caused by a timeout), the `xqc_hs_buffer_t`s in these lists will leak.

### Steps To Reproduce

I found this bug in a customized version, so I'm not sure this can be reproduced.

**Comment by Kulsk** [comment]
fixed on #287
