### ISSUE TITLE
[Bug]: 英文注释拼写错误

### ISSUE THREAD

**Issue by adcen0107** [alibaba/xquic#208]
### What happened?

http3/xqc_h3_request.c的xqc_h3_request_send_headers函数中，有两处英文注释拼写错误：

错误一：
    /*  malloc a new  move pesudo headers in the front of list */

错误二：
    /* make pesudo headers first */

pesudo应该改为pseudo。

### Steps To Reproduce

观察代码即可。

### Relevant log output

```shell
无
```

**Comment by yuanbo-zhang** [comment]
Dear      您好，邮件我已收到 ！BestwishThink's张渊博
