### ISSUE TITLE
[Bug]: Is there any serious test on xquic?

### ISSUE THREAD

**Issue by Luffbee** [alibaba/xquic#265]
### What happened?

I found many memory leak bugs, it seems xquic is not tested in extreme scenarios (e.g. high loss rate).

### Steps To Reproduce

See my issues.

**Comment by Yanmei-Liu** [comment]
Actually we have tested in extreme scenarios (e.g 20 percent loss ratio). 
I think the problem you found is that the packet memory is cached in the queue under xqc_connection, which is reused many times but not released until the connection resource is freed. It's a lazy release mechanism considering performance. By the way, we limited the maximum packet queue length per connection.
