### ISSUE TITLE
[Bug]: demo_server and demo_client create empty key log files

### ISSUE THREAD

**Issue by MPK1** [alibaba/xquic#311]
### What happened?

If I run the demo binaries and use `-k` to specify a path for the SSL key log file, the files (one for each endpoint) are created but remain empty. The connection including the transmission of a testfile works as expected.

### Steps To Reproduce

1. Build XQUIC (I used commit 78cf6d1e50d4ebe8fb51fddfbdb55d36a5798386 on Debian 11 x86_64 with BoringSSL)
2. Run demo_server and demo_client and transfer a arbitrary file (I used a single 128MB file) 
3. After successful transmission, look into the SSL key log files.

I used the following commands to start server/client:
`./demo_server -p 4433 -D www -c c -C -l d -L logs/server.log -k logs/server-keys.log`
`./demo_client -a 10.0.0.2 -p 4433 -u "https://server:4433/testfile" -D downloads -K 120 -c c -C -l d -t 120 -L logs/client.log -k logs/client-keys.log`

(EDIT: I'm aware that the demo binaries are for interop testing. That's actually what I'm trying to do.)

**Comment by Kulsk** [comment]
build with -DXQC_PRINT_SECRET=1
