### ISSUE TITLE
[Bug]: xqc_build.sh build iOS failed

### ISSUE THREAD

**Issue by RuiqiZhou** [alibaba/xquic#33]
### What happened?

As discussions #21 , build iOS failed using `xqc_build.sh`

### Steps To Reproduce

As discussions #21 

> macOS 11.4
> Xcode 12.5
> cmake version 3.21.2
> 
> 1.export IOS_CMAKE_TOOLCHAIN="xx/xquic/cmake/ios.toolchain.cmake"
> 2. sh xqc_build.sh ios ios_build ios_release xxx/xquic/third_party/boringssl
> 
> output:
> [ 1%] Generating crypto_test_data.cc
> make[2]: *** No rule to make target xxx/xquic/bssl_symbols.txt', needed by third_party/boringssl/symbol_prefix_include/boringssl_prefix_symbols.h'. Stop.
> make[1]: *** [third_party/boringssl/CMakeFiles/boringssl_prefix_symbols.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 1%] Building CXX object third_party/boringssl/CMakeFiles/boringssl_gtest.dir/third_party/googletest/src/gtest-all.cc.o
> [ 1%] Building CXX object third_party/boringssl/CMakeFiles/crypto_test_data.dir/crypto_test_data.cc.o
> [ 1%] Built target crypto_test_data
> [ 1%] Linking CXX static library ../../outputs/libboringssl_gtest.a
> [ 1%] Built target boringssl_gtest
> make: *** [all] Error 2

**Comment by dourgulf** [comment]
Same problem

**Comment by lurker-Chen** [comment]
> Same problem

https://github.com/alibaba/xquic/discussions/21

**Comment by RuiqiZhou** [comment]
> Same problem

Hi, there is a temporary solution: https://github.com/alibaba/xquic/discussions/21#discussioncomment-1947115

**Comment by dourgulf** [comment]
Find a solution keep borningssl prefix
1. Change borningssl CMakeLists.txt, remove the contents of the red box
![image](https://user-images.githubusercontent.com/1005591/149257315-7710abdf-b051-47a7-8164-9e94c3c14b67.png)

2. Change xquic cmake/CMakeLists.txt,
![image](https://user-images.githubusercontent.com/1005591/149257818-8554a20c-f78d-4cc0-950c-f8e95e75a406.png)
comment line `# include_directories(${SSL_PATH}/symbol_prefix_include)`
change to `include_directories(${CMAKE_CURRENT_BINARY_DIR}/${SSL_PATH}/symbol_prefix_include)`

**Comment by lurker-Chen** [comment]
Thanks you for your solution ! It only needs to modify borningssl CMakeLists.txt. Change as what you do in step 1 or delete the command "DEPENDS util/make_prefix_headers.go ${CMAKE_BINARY_DIR}/${BORINGSSL_PREFIX_SYMBOLS} ". It is similar to [https://stackoverflow.com/questions/4010212/cmake-struggling-with-add-custom-command-dependencies](url)

**Comment by lurker-Chen** [comment]
It is not usually necessary to use prefix_symbols. If you really need the feature, you should update bssl_symbols.txt using util/read_symbols.go in boringssl when boringssl is updated.
![image](https://user-images.githubusercontent.com/97525334/149267590-ec6bde51-ec83-4d2b-bc14-6c4d23adfb22.png)
[https://github.com/google/boringssl/blob/master/BUILDING.md](url)
