### ISSUE TITLE
[Bug]: demo_client can not enable mulitipath feature on two different netdevice;

### ISSUE THREAD

**Issue by linsy007** [alibaba/xquic#333]
### What happened?

./demo_client -l e -L clog -d -k ./ckeys.log -K 60 -U https://xquic_server:443/1g -A "h3" -i eth1 -i eth0 -M 
xqc_demo_cli_init_user_path ---> xqc_demo_cli_create_socket(user_path, &ctx->args->net_cfg, 0);
   create  two path on eth1 dev 

### Steps To Reproduce

./demo_client -l e -L clog -d -k ./ckeys.log -K 60 -U https://xquic_server:443/1g -A "h3" -i eth1 -i eth0 -M 
xqc_demo_cli_init_user_path ---> xqc_demo_cli_create_socket(user_path, &ctx->args->net_cfg, path_seq);
   create  one path on eth1 dev, and anther path on eth0 dev

**Comment by Kulsk** [comment]
is there any std print log?

**Comment by yangfurong** [comment]
This issue was fixed by PR #338
