### ISSUE TITLE
windows编译失败

### ISSUE THREAD

**Issue by chenhongquan** [alibaba/xquic#343]
windows 10 10.0.19045
visual studio 2022 community
xquic 1.6.2
![image](https://github.com/alibaba/xquic/assets/8565253/9379bdf8-98a4-49c4-b2d2-17a0d99cc4ce)
操作到MSBuild.exe xquic.vcxproj的时候报错：
![image](https://github.com/alibaba/xquic/assets/8565253/d32e3fc1-5c03-4967-9eee-fdcc09251928)

**Comment by yuanbo-zhang** [comment]
你好回退到v1.3.0版本试试，最新几个版本因新功能没适配windows平台暂不支持，下个版本会恢复支持

**Comment by chenhongquan** [comment]
v1.3.0-beta版本也有问题，按照platforms.md的步骤操作，在MSBuild.exe xquic.vcxproj的时候报错找不到 openssl/ssl.h, openssl/err.h

**Comment by yuanbo-zhang** [comment]
Dear      您好，邮件我已收到 ！BestwishThink's张渊博

**Comment by yuanbo-zhang** [comment]
cmake -DSSL_TYPE=${SSL_TYPE_STR} -DSSL_PATH=${SSL_PATH_STR} -DSSL_INC_PATH=${SSL_INC_PATH_STR} -DSSL_LIB_PATH=${SSL_LIB_PATH_STR} ..

这里${xxx} 是指带，需要根据前面自己编译和使用的ssl位置和类型进行指导
