### ISSUE TITLE
[Bug]: No transmission speed difference between single path and multipath with minrtt scheduler

### ISSUE THREAD

**Issue by liebentRC** [alibaba/xquic#356]
### What happened?

Hi, Im a student learning about multipath transmission, I heard that xquic support many kinds of multipath scheduler.
However, when I make a comparision between single path trans and multipath trans with minrtt, I found there's no obvious difference between them, although between isomorphic link.

Then I will describe my experimental procedure in detail

experiment one: large file download with high bindwith and low lantency
path feature:
path 0: rtt 2.5ms，bindwidth: about 700Mbit, packet loss rate: almost 0
path 1: rtt 2.5ms，bindwidth: about 700Mbit, packet loss rate: almost 0
cc method: bbr
experimental result:
single path trans:
FCT: 11.32s speed: 92630KB/s
![image](https://github.com/alibaba/xquic/assets/149153237/bd916f9b-7395-4706-91dd-3a7262951c06)
cwnd changes
![image](https://github.com/alibaba/xquic/assets/149153237/67d7a08d-afb5-4258-ae25-10603f58605b)
path srtt changes
![image](https://github.com/alibaba/xquic/assets/149153237/fd1720d9-9e5a-4908-a5c8-d42cc8e49626)

minrtt scheduler trans:
FCT: 11.52s speed: 91012KB/s(I tried many times, overall transmission speed is almost the same as that of single path)
![image](https://github.com/alibaba/xquic/assets/149153237/22c1c961-b272-4759-8a70-4939e44812f8)
cwnd changes
![image](https://github.com/alibaba/xquic/assets/149153237/58e54175-c96b-4f38-98b5-a6ab359c0404)
path srtt changes
![image](https://github.com/alibaba/xquic/assets/149153237/c42021c2-4e46-4f03-b187-2771076ac98f)

I initially suspected that the bandwidth was too high and the performance bottleneck of the transfer was the packet processing
So I used TC tool to limit the bandwidth and increase the transmission delay

experiment two: small file download with low bindwith and high latency
path feature:
path 0: rtt 102ms, bindwith: 10Mbit, packet loss rate: almost 0
path 1: rtt 102ms, bindwith: 10Mbit, packet loss rate: almost 0

this time I use reno and bbr

single path trans with reno
![image](https://github.com/alibaba/xquic/assets/149153237/5ce44c2e-c4a6-43aa-beca-185f8e6b6c6e)
single path cwnd change(reno)
![image](https://github.com/alibaba/xquic/assets/149153237/4a06830c-6743-44ec-b978-cf452fa90030)
single path srtt change(reno)
![image](https://github.com/alibaba/xquic/assets/149153237/9fb0e7dd-5d31-4b12-8a7f-83c614d737b2)

multipath trans with reno
![image](https://github.com/alibaba/xquic/assets/149153237/a727f05b-2ae4-44d9-8e23-c6cf5c6adc05)
minrtt cwnd change （reno）
![image](https://github.com/alibaba/xquic/assets/149153237/3376cce7-4de6-4ecb-98c9-54c6db867d14)
minrtt path srtt change (reno)
![image](https://github.com/alibaba/xquic/assets/149153237/26514033-9075-4e93-9ed3-7335ef4fce12)

single path trans with bbr
![image](https://github.com/alibaba/xquic/assets/149153237/94cd053b-b96a-47c7-aa3a-df886f5a102a)
single path cwnd change (bbr)
![image](https://github.com/alibaba/xquic/assets/149153237/18905ffe-fc2c-45b3-8bee-9023a7cd09f8)
single path srtt change(bbr)
![image](https://github.com/alibaba/xquic/assets/149153237/75415ee4-bab4-4471-a1d0-66b8a4ec94e7)

multipath trans with bbr
![image](https://github.com/alibaba/xquic/assets/149153237/353f6504-cd35-4dba-99e4-a4330bdcfbd1)
minrtt cwnd change (bbr)
![image](https://github.com/alibaba/xquic/assets/149153237/f9f0e6b2-9f44-452e-85d6-fcc43530a3f8)
minrtt path srtt change(bbr)
![image](https://github.com/alibaba/xquic/assets/149153237/27953754-3a7a-437b-88c8-864f5edccbaa)

I don't know what happened here, when I check codes in minrtt scheduler, I can't find any problem.

Is any problem in flow control or something else?

### Steps To Reproduce

Use minrtt and single path to download files

**Comment by yangfurong** [comment]
Please describe your testbed and the commands to launch the XQUIC client/server in more detail. 
1. How did you emulate two paths with TC? What were the TC commands?
2. What were the commands to launch test_client/test_server?

In our test, MPQUIC with the minrtt scheduler can aggregate the bandwidth of two symmetric paths.

**Comment by Thuwzq** [comment]
problem has been solved in xquic opensource communication group, the reason is handshake done has been blocked by first stream data, xquic group will optimize in next release version. Issue done

**Comment by liebentRC** [comment]
Issue has been solved in opensource group. handshake done is blocked by first request stream data, which cause second path can not be established. This will be optimized in next version. Issue done

**Comment by a-andre** [comment]
@yangfurong could you share the commands you used to test multipath xquic?

How can demo and test application make use of multipath (judging by their code they can only handle a single IP address and a single port)?
