### ISSUE TITLE
How to use the connection migration

### ISSUE THREAD

**Issue by LLL2000L** [alibaba/xquic#366]
How can I use the connection migration feature or see the effect of QUIC connection migration? I would appreciate your guidance. Thank you.

**Comment by yangfurong** [comment]
Currently, XQUIC only supports passive migration. That said, the connection is able to survive from the change of the underlying network address. There are test options in test_client and demo_client to test that feature (e.g., the -e option in demo_client). 

For active migration (e.g., migrating a path from a Wi-Fi interface to a cellular interface), we suggest you use XQUIC's multipath feature (e.g., creating a new path over the new interface and closing the old one).
