### ISSUE TITLE
[Bug]: babassl cannot be compiled without makefile

### ISSUE THREAD

**Issue by cherylsy** [alibaba/xquic#408]
### What happened?

Current recommended babassl version cannot be compiled, with msg `make: *** No targets specified and no makefile found.  Stop.` :
![D8F3ADB5-5943-4328-BDEC-3CBC0387CA7A](https://github.com/alibaba/xquic/assets/140379011/7c5c5c9e-0f8d-40cd-849e-f681bd8f1bfd)

### Steps To Reproduce

Just clone the latest release and try the cmd of ` Build with BabaSSL(Tongsuo)`.

**Comment by Kulsk** [comment]
not reproduced
