### ISSUE TITLE
[Bug]: windows 系统下编译失败？

### ISSUE THREAD

**Issue by fashion1840** [alibaba/xquic#411]
### What happened?

按照”Platforms.md“文档中windows 编译xquic 失败了

windows 10 
visual studio 2019
xquic 1.7.1

### Steps To Reproduce

使用boringssl 可以正常编译出lib来，按下面的步骤编译xquic工程：

step 3：build xquic
mkdir build
cd build
cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DBUILD_SHARED_LIBS=OFF -DSSL_TYPE="boringssl" -DSSL_PATH="E:\demos\lsquic\boringssl" ..
MSBuild.exe xquic.vcxproj

![2024-04-17_155802](https://github.com/alibaba/xquic/assets/15226848/50fa2301-ccde-4c66-98e4-7791827afb10)

![2024-04-17_155552](https://github.com/alibaba/xquic/assets/15226848/d7ad1597-131a-4abb-912b-fa31b40a9d09)

![2024-04-17_155656](https://github.com/alibaba/xquic/assets/15226848/cfa8e0a2-c131-4df9-aa86-596f90d58e0d)

**Comment by Yanmei-Liu** [comment]
Fixed by PR #413 (merged)
