### ISSUE TITLE
[Bug]: link error:  undefined reference to `xqc_engine_get_conn_by_scid'

### ISSUE THREAD

**Issue by zheisure** [alibaba/xquic#464]
### What happened?

如标题所示，在使用xquic动态库时，发生链接错误undefined reference to `xqc_engine_get_conn_by_scid'

### Steps To Reproduce

编译环境：
CMake Version: 3.29.7
CMake Generator: Ninja
Operating System:  Ubuntu22.04（Linux 5.15.167.4-microsoft-standard-WSL2）
Compiler: GNU 11.4.0
Building with dynamic libssl

编写demo，demo中只要调用了 `xqc_engine_get_conn_by_scid`就会发生链接错误

### Relevant log output

```shell
[build] /usr/bin/ld: code/client/CMakeFiles/client.dir/App.cpp.o: in function `App::On_conn_create_notify(xqc_connection_s*, xqc_cid_s const*, void*, void*)':
[build] /***/App.cpp:28: undefined reference to `xqc_engine_get_conn_by_scid'
[build] collect2: error: ld returned 1 exit status
```

**Comment by Yanmei-Liu** [comment]
Thanks for the solution in #465. The PR has been merged.
