### ISSUE TITLE
when will xquic support windows?

### ISSUE THREAD

**Issue by GreenValue** [alibaba/xquic#65]
### Before request a new feature

- [X] I have searched the [issues](https://github.com/alibaba/xquic/issues) of this repository and believe that this is not a duplicate.

### Describe the feature you'd like supported

when will xquic support windows?
I want to use xquic to trasnfer file in windows exe.

**Comment by RuiqiZhou** [comment]
Not in the short term. Please see our [milestones](https://github.com/alibaba/xquic/milestones) for what we are currently doing.
