### ISSUE TITLE
[Feature]: simple server/client without http3

### ISSUE THREAD

**Issue by ktprime** [alibaba/xquic#66]
### Before request a new feature

- [X] I have searched the [issues](https://github.com/alibaba/xquic/issues) of this repository and believe that this is not a duplicate.

### Describe the feature you'd like supported

Can provide some demo such as echo server/client which is not including http3.

**Comment by RuiqiZhou** [comment]
OK, we'll provide a simple sample next month.

**Comment by Kulsk** [comment]
test_client with -N option might satisfy your requirement, with a self-defined ALPN named transport, providing the features of rfc8999 to rfc9002.
