### ISSUE TITLE
[Feature]: Provide an android example or integrate with curl etc.

### ISSUE THREAD

**Issue by ag2s20150909** [alibaba/xquic#72]
### Before request a new feature

- [X] I have searched the [issues](https://github.com/alibaba/xquic/issues) of this repository and believe that this is not a duplicate.

### Describe the feature you'd like supported

Provide an android example or integrate with curl etc.
Provides java api like cronet, or integration with curl like other quic libraries
https://github.com/curl/curl/blob/master/docs/HTTP3.md

**Comment by Kulsk** [comment]
Another opensource project will be released by Aliwolf group in future, which is used on Android and iOS, it might be opened on github around the end of March.
But curl integration will not be provided.
